---
- name: Install packages
  dnf:
    name: '{{ fedoraPackages }}'
    state: present

- name: Add general flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpacks }}"
