---
- name: Add general flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpacks }}"

# Setup termite repo
- name: Enable project Test of the user schlupov
  community.general.copr:
    name: skidnik/termite

# Install codium aka vscode oss repo
- name: codium gpg
  rpm_key:
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
    state: present

- name: codium repo
  yum_repository:
    name: vscodium.repo
    description: VS codium aka vscode oss
    baseurl: https://download.vscodium.com/rpms/
    gpgcheck: true
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

# Install packages
- name: Install packages
  dnf:
    name: '{{ fedoraPackages }}'
    state: present
