---
- name: Add general flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  with_items: "{{ flatpacks }}"

# Setup ghostty repo
- name: Enable Ghostty repo
  community.general.copr:
    name: pgdev/ghostty

# Setup starship repo
- name: Enable project starship
  community.general.copr:
    name: atim/starship

# Install vscode gpg repo
- name: vscode gpg
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: vscode repo
  yum_repository:
    name: vscode.repo
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

# Install codium aka vscode oss repo
- name: google cli gpg
  rpm_key:
    key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present

- name: google repo
  yum_repository:
    name: GoogleCloudCLI
    description: Google Cloud CLI
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

# Install packages
- name: Install packages
  dnf:
    name: "{{ fedoraPackages }}"
    state: present

# Disable SElLinux, I'm sorry
- name: Disable SELinux
  selinux:
    state: disabled

- name: Enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
