---
- hosts: all
  remote_user: edvin
  become: yes
  become_user: root
  become_method: su
  tasks:

  - name: install dependecies
    package:
      name:
        - vim-common
        - vim-enhanced
        - epel-release-7-9.noarch
        - git
      state: latest

  - name: write the config
    template:
      src: /home/edvin/.vimrc
      dest: /root/.vimrc

  - name: write the config
    copy:
      src: /home/edvin/.vim
      dest: /root/
